/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#define CONFIG_TCC_STATIC 1
#define GCC_MAJOR 
#define GCC_MINOR 
#define HOST_ARM 1
#define TCC_ARM_VERSION 4
#define TCC_VERSION "0.9.26"
#define CONFIG_NOLDL

